# Generated by Django 3.1 on 2020-08-28 06:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=100)),
                ('number_of_adults', models.IntegerField(default=0)),
                ('number_of_children', models.IntegerField(default=0)),
                ('enquiry_status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_category', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('amount_per_head', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='purchase date')),
                ('purchase_description', models.CharField(max_length=100)),
                ('purchase_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('salary', models.FloatField(default=0.0)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='booking_date')),
                ('checkin_date', models.DateTimeField(verbose_name='check_in_time')),
                ('checkout_date', models.DateTimeField(verbose_name='check_out_date')),
                ('number_of_people', models.IntegerField(default=0)),
                ('booking_amount', models.FloatField(default=0.0)),
                ('paid_status', models.CharField(max_length=100)),
                ('booking_status', models.CharField(choices=[('p', 'pending'), ('b', 'Booked'), ('c', 'Canceled')], max_length=1)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Online Transfer', 'Online Transfer'), ('Bank Deposit', 'Bank Deposit')], default='Cash', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.package_detail')),
            ],
        ),
    ]
