# Generated by Django 3.1 on 2020-08-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_auto_20200828_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('p', 'Pending'), ('b', 'Booked'), ('c', 'Canceled')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_status',
            field=models.CharField(default='unpaid', max_length=100),
        ),
    ]
