# Generated by Django 3.1 on 2020-08-29 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0003_auto_20200829_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='booking_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check_in_time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default='', verbose_name='check_out_date'),
        ),
    ]
