# Generated by Django 3.1 on 2020-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0004_auto_20200829_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(blank=True, verbose_name='check_out_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mode_of_payment',
            field=models.CharField(choices=[('', 'Select'), ('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Online Transfer', 'Online Transfer'), ('Bank Deposit', 'Bank Deposit')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='p', max_length=100),
        ),
    ]
