# Generated by Django 3.1 on 2020-08-30 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_auto_20200829_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='booking_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('p', 'Pending'), ('b', 'Booked'), ('c', 'Canceled')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(blank=True, verbose_name='check_in_time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='u', max_length=100),
        ),
    ]
