# Generated by Django 3.0.4 on 2020-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0007_auto_20200903_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
