# Generated by Django 3.0.4 on 2020-09-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0010_auto_20200904_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='amount_per_head',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='purchase_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
