# Generated by Django 3.0.4 on 2020-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0011_auto_20200904_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=100),
        ),
    ]
