# Generated by Django 3.0.4 on 2020-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0012_auto_20200905_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
