# Generated by Django 3.0.4 on 2020-09-05 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0014_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='review_date'),
        ),
    ]
