# Generated by Django 3.1 on 2020-09-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0015_auto_20200905_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
    ]
